name: Report a bug
description: Create a bug report
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for your bug report!**

        First, be sure you are running the [latest version of the Bed Cooldown plugin](https://github.com/rfinnie/OctoPrint-BedCooldown/releases).

        You will also need to [enable debugging on the plugin](https://docs.octoprint.org/en/master/configuration/logging_yaml.html).
        This may be done through the *Settings* > *OctoPrint* > *Logging* > *Logging Levels* section.
        Select the "octoprint.plugins.bedcooldown" Name, and make sure Level is "DEBUG".
        Save, then restart OctoPrint.

        Finally, when submitting a bug report, you **must** [include a Systeminfo Bundle](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887), produced after the print completed.
        This allows the developer to examine the debug logs produced during the print.

        Thank you for your help!
  - type: textarea
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here. Tell us what you were trying to do
        step by step, and what happened that you did not expect.

        Provide a clear and concise description of what the problem is and include as many
        details as possible.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
